version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: rodmidde/jenkins-slave-python
    steps:
      - checkout
      - run:
          pip install pandocfilters 
      - run:
          python astah-test.py 
